[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "dependencies"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc = "0.8.28"
evm_version = "paris"

fs_permissions = [{ access = "read-write", path = "config/" }]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
holesky = "${RPC_HOLESKY}"
amoy = "${RPC_POLYGON_AMOY}"
polygon = "${}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { key = "${ETHERSCAN_MAINNET_KEY}" }
holesky = { key = "${ETHERSCAN_MAINNET_KEY}" }
amoy = { key = "${POLYGON_MAINNET_KEY}" }
polygon = { key = "${POLYGON_MAINNET_KEY}" }



[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
